# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdeleFramework < Formula
  desc ""
  homepage ""
  version "1.0.0-ci.20250905.1303+sha.1b1f765"

  on_macos do
    on_intel do
      url "https://github.com/harrisonde/adele-framework/releases/download/1.0.0-ci.20250905.1303+sha.1b1f765/adele_darwin_x86_64"
      sha256 "2a51e3c93b72083a096eec4805d822d7aba3c241897b3112a5512f8d0e1be1c5"

      def install
        bin.install "adele_darwin_x86_64" => "adele"
      end
    end
    on_arm do
      url "https://github.com/harrisonde/adele-framework/releases/download/1.0.0-ci.20250905.1303+sha.1b1f765/adele_darwin_arm64"
      sha256 "fdf3601292fada56a9b1d573e84ea6add590929772dc791673e2125188587f6b"

      def install
        bin.install "adele_darwin_arm64" => "adele"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrisonde/adele-framework/releases/download/1.0.0-ci.20250905.1303+sha.1b1f765/adele_linux_x86_64"
        sha256 "2c7d7c39995d96b4d7d328d0871299e1914ee81975137f2649a2acf924ae5579"

        def install
          bin.install "adele_linux_x86_64" => "adele"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrisonde/adele-framework/releases/download/1.0.0-ci.20250905.1303+sha.1b1f765/adele_linux_arm64"
        sha256 "aa43e001f0d69ac29a1d8d9fba2f87b31977921c948205124d5c5b95d48939bf"

        def install
          bin.install "adele_linux_arm64" => "adele"
        end
      end
    end
  end
end
