# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  release:
    runs-on: ["self-hosted", "macOS"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.4
      - name: write tag to adele.go
        run: go run .github/workflows/semantic-release-write-version.go
      - name: install quill
        run: curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b .tmp/quill v0.4.1
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUILL_SIGN_P12: ${{ secrets.CERTIFICATES_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          QUILL_NOTARY_KEY: ${{ secrets.QUILL_NOTARY_KEY }}
          QUILL_NOTARY_KEY_ID: ${{ secrets.QUILL_NOTARY_KEY_ID }}
          QUILL_NOTARY_ISSUER: ${{ secrets.QUILL_NOTARY_ISSUER}}
